package com.example.assetflowlogin.enums;

public enum NotificationType {
    ASSET_ASSIGNED,
    ASSET_RETURNED,
    TRANSFER_REQUESTED,
    TRANSFER_APPROVED,
    TRANSFER_REJECTED,
    BOOKING_CREATED,
    BOOKING_CANCELLED,
    BOOKING_REMINDER,
    MAINTAINENCE_REQUESTED,
    MAINTAINENCE_APPROVED,
    MAINTAINENCE_REJECTED,
    MAINTAINENCE_RESOLVED,
    AUDIT_CREATED,
    AUDIT_DISCREPANCY,
    OVERDUE_RETURN,
    SYSTEM
}
